"""Lightweight workspace templates for quick project bootstrapping."""
from __future__ import annotations

from pathlib import Path
from typing import Dict


class WorkspaceTemplateManager:
    """Create simple starter projects without external dependencies."""

    def __init__(self) -> None:
        self._templates: Dict[str, dict[str, str]] = {
            "python-basic": {
                "README.md": "# New Python Project\n\nGenerated by Ghostline Studio.",
                "main.py": "print('Hello from Ghostline Studio!')\n",
                "requirements.txt": "",
            },
            "notes": {
                "README.md": "# Notes workspace\n\nTrack quick notes and todos.",
                "notes/todo.md": "- [ ] First task\n",
            },
        }

    def list_templates(self) -> list[str]:
        return sorted(self._templates.keys())

    def create(self, template: str, destination: str | Path) -> Path:
        destination_path = Path(destination).resolve()
        destination_path.mkdir(parents=True, exist_ok=True)
        files = self._templates.get(template)
        if files is None:
            raise ValueError(f"Unknown template: {template}")

        for relative_path, content in files.items():
            target = destination_path / relative_path
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content)

        return destination_path
